---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  labels:
    name: dbdata
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-ceph-block-nvme
  resources:
    requests: 
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwdata
  namespace: sarah-farhood-org
  labels:
    name: wwwdata
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-ceph-block-nvme
  resources:
    requests: 
      storage: 128Gi