---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  labels:
    name: dbdata
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests: 
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwdata
  namespace: sarah-farhood-org
  labels:
    name: wwwdata
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn-perpetual
  resources:
    requests: 
      storage: 128Gi